# Generated by Django 2.0.4 on 2018-04-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180420_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Course'),
        ),
    ]
