# Generated by Django 2.0.4 on 2018-04-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180420_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentration',
            name='conc_code',
        ),
    ]
