# Generated by Django 2.0.4 on 2018-04-20 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_concentration_req_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentration',
            name='conc_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Department'),
        ),
    ]
