# Generated by Django 2.0.4 on 2018-04-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180420_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(to='home.Class'),
        ),
        migrations.AlterField(
            model_name='course',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Area'),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='max_common_with_major',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='pdfs_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
