# Generated by Django 2.0.4 on 2018-04-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180420_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='_course_prereqs_+', to='home.Course'),
        ),
    ]
