# Generated by Django 2.0.4 on 2018-04-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180420_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_list',
            name='req_lists_inside',
            field=models.ManyToManyField(blank=True, related_name='_req_list_req_lists_inside_+', to='home.Req_List'),
        ),
    ]
