# Generated by Django 2.0.4 on 2018-04-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_concentration_conc_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentration',
            name='code',
        ),
    ]
