# Generated by Django 2.0.4 on 2018-04-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180420_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concentration',
            old_name='code',
            new_name='conc_code',
        ),
    ]
