# Generated by Django 2.0.4 on 2018-04-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_course_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='x',
            new_name='course_ref',
        ),
    ]
