# Generated by Django 2.0.4 on 2018-04-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180420_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='course_ref',
        ),
        migrations.AlterField(
            model_name='listing',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Department'),
        ),
    ]
