# Generated by Django 2.0.4 on 2018-05-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classnum', models.CharField(max_length=10)),
                ('enroll', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('starttime', models.TimeField()),
                ('section', models.CharField(max_length=4)),
                ('endtime', models.TimeField()),
                ('roomnum', models.CharField(blank=True, max_length=15, null=True)),
                ('days', models.CharField(max_length=9)),
                ('bldg', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=3)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('courseid', models.IntegerField()),
                ('descrip', models.TextField()),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Area')),
                ('classes', models.ManyToManyField(to='home.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Req_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_counted', models.IntegerField(default=1)),
                ('min_needed', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('double_counting_allowed', models.BooleanField(default=False)),
                ('max_common_with_major', models.IntegerField(blank=True, null=True)),
                ('pdfs_allowed', models.IntegerField(blank=True, null=True)),
                ('completed_by_semester', models.IntegerField(default=8)),
                ('course_list', models.ManyToManyField(blank=True, to='home.Course')),
                ('req_lists_inside', models.ManyToManyField(blank=True, to='home.Req_List')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=1)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(max_length=100)),
                ('plans', models.ManyToManyField(to='home.Plan')),
            ],
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='semester',
            field=models.ManyToManyField(to='home.Semester'),
        ),
        migrations.AddField(
            model_name='plan',
            name='saved_courses',
            field=models.ManyToManyField(to='home.SavedCourse'),
        ),
        migrations.AddField(
            model_name='course',
            name='listings',
            field=models.ManyToManyField(to='home.Listing'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='_course_prereqs_+', to='home.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(to='home.Professor'),
        ),
        migrations.AddField(
            model_name='concentration',
            name='conc_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Department'),
        ),
        migrations.AddField(
            model_name='concentration',
            name='contacts',
            field=models.ManyToManyField(to='home.Contact'),
        ),
        migrations.AddField(
            model_name='concentration',
            name='req_lists',
            field=models.ManyToManyField(to='home.Req_List'),
        ),
        migrations.AddField(
            model_name='concentration',
            name='urls',
            field=models.ManyToManyField(to='home.URL'),
        ),
    ]
