# Generated by Django 2.0.4 on 2018-04-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Req_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_counted', models.IntegerField()),
                ('min_needed', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('double_counting_allowed', models.BooleanField()),
                ('max_common_with_major', models.IntegerField()),
                ('pdfs_allowed', models.BooleanField()),
                ('completed_by_semester', models.IntegerField()),
                ('req_list_inside', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Req_List')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
                ('degree', models.CharField(max_length=3)),
                ('year', models.IntegerField()),
                ('contacts', models.ManyToManyField(to='home.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='urls',
            field=models.ManyToManyField(to='home.URL'),
        ),
    ]
