# Generated by Django 2.0.4 on 2018-05-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='home.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('S', 'Spring'), ('F', 'Fall')], max_length=6)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(max_length=100)),
                ('saved_courses', models.ManyToManyField(to='home.SavedCourse')),
            ],
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='semester',
            field=models.ManyToManyField(to='home.Semester'),
        ),
    ]
