# Generated by Django 2.0.4 on 2018-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseid',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='semester',
            name='season',
            field=models.CharField(max_length=1),
        ),
    ]
