# Generated by Django 2.0.4 on 2018-04-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='x',
        ),
        migrations.AlterField(
            model_name='course',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Area'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.ManyToManyField(blank=True, related_name='_course_prereqs_+', to='home.Course'),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='completed_by_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='course_list',
            field=models.ManyToManyField(blank=True, to='home.Course'),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='double_counting_allowed',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='max_common_with_major',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='max_counted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='min_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='pdfs_allowed',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='req_list',
            name='req_lists_inside',
            field=models.ManyToManyField(blank=True, related_name='_req_list_req_lists_inside_+', to='home.Req_List'),
        ),
    ]
