# Generated by Django 2.0.4 on 2018-05-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.ManyToManyField(to='home.Semester'),
        ),
    ]
