# Generated by Django 2.0.4 on 2018-05-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='saved_courses',
            field=models.ManyToManyField(blank=True, to='home.SavedCourse'),
        ),
    ]
