# Generated by Django 2.0.4 on 2018-05-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180505_1719'),
        ('home', '0002_course_semesters'),
    ]

    operations = [
    ]
