# Generated by Django 2.0.4 on 2018-05-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180509_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_list',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
