# Generated by Django 2.0.4 on 2018-05-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180502_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_courses', models.ManyToManyField(to='home.SavedCourse')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_courses',
        ),
        migrations.AddField(
            model_name='user',
            name='plans',
            field=models.ManyToManyField(to='home.Plan'),
        ),
    ]
