# Generated by Django 2.0.4 on 2018-05-10 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180509_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcourse',
            name='course',
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Course'),
        ),
        migrations.RemoveField(
            model_name='savedcourse',
            name='semester',
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Semester'),
        ),
    ]
