# Generated by Django 2.0.4 on 2018-05-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plans',
        ),
        migrations.AddField(
            model_name='plan',
            name='conc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Concentration'),
        ),
        migrations.AddField(
            model_name='plan',
            name='degree',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Plan'),
        ),
    ]
