# Generated by Django 2.0.4 on 2018-04-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='listings',
            field=models.ManyToManyField(to='home.Listing'),
        ),
    ]
