# Generated by Django 2.0.4 on 2018-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180425_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='roomnum',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
