# Generated by Django 2.0.4 on 2018-04-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_listing_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='department',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='x',
        ),
        migrations.RemoveField(
            model_name='course',
            name='listings',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
