# Generated by Django 2.0.4 on 2018-04-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_concentration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentration',
            name='req_lists',
            field=models.ManyToManyField(to='home.Req_List'),
        ),
    ]
